"use client";
import "./globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import CartPage from "@/components/cartPage/cartPage";
import { useState } from "react";
import ModalMenu from "@/components/modalMenu/modalMenu";

// export const metadata = {
//   title: "Audiophile Website",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [modal, setModal] = useState(false);
  const [modal1, setModal1] = useState(false);
  const [modal2, setModal2] = useState(false);

  const toggleModal = () => setModal(!modal); // Toggle function

  const handleOpenModal1 = () => {
    setModal1((prevstate) => !prevstate);
  };

  const handleOpenModal2 = () => {
    setModal2((prevstate) => !prevstate);
  };

  return (
    <html lang="en">
      <body className={`h-fit antialiased`}>
        <div className="sticky top-0">
          <Header
            closeModal={() => setModal2(false)}
            toggleModal={toggleModal}
            openModal1={handleOpenModal1}
            openModal2={handleOpenModal2}
          />
        </div>

        {/* Modal for Cart */}
        {modal1 && (
          <div className="fixed h-screen w-full bg-[#6b7280c4] flex justify-center overflow-auto p-8">
            <div className="fixed md:top-[5.5rem] md:right-0 p-8 md:m-6 rounded-[7px] md:w-[25rem] w-[90%] h-fit bg-white shadow-lg z-50 cart-modal ${modal ? 'open' : ''}`}">
              <CartPage closeModal={() => setModal1(false)} />
            </div>
          </div>
        )}
        {/* Modal for Menu */}
        {modal2 && (
          <div className="fixed h-screen w-full bg-[#6b7280c4] flex justify-center">
            <div className="fixed overflow-visible rounded[7px] px-4 pb-4 w-full h-fit bg-white shadow-lg z-50 menu-modal">
              <ModalMenu
                closeModal={() => setModal2(false)}
              />
            </div>
          </div>
        )}

        {children}
        <Footer />
      </body>
    </html>
  );
}
